### ISSUE TITLE
About the cov_shift in the model.

### ISSUE THREAD

**Issue by shangwei5** [volflow/DeFlow#2]
Why the conv_shift in your "DeFlow-DPED-RWSR-100k.pth" is 0? And I retrian Deflow on my own dataset, but the conv_shift is 0, too. Is it common? Why does this happen？Looking forward to your reply,thanks.

**Comment by volflow** [comment]
Hi ShangWei,
thank you for raising this issue. I checked the pretrained models and the cov_shit is indeed 0. 
Could you try setting 'std_init_shift: 0.01' or to some other small value in the config, and see if this fixes it?
I will also investigate this further.
Best,
Valentin

**Comment by shangwei5** [comment]
> Hi ShangWei,
> thank you for raising this issue. I checked the pretrained models and the cov_shit is indeed 0.
> Could you try setting 'std_init_shift: 0.01' or to some other small value in the config, and see if this fixes it?
> I will also investigate this further.
> Best,
> Valentin

**Comment by shangwei5** [comment]
> Hi ShangWei,
> thank you for raising this issue. I checked the pretrained models and the cov_shit is indeed 0.
> Could you try setting 'std_init_shift: 0.01' or to some other small value in the config, and see if this fixes it?
> I will also investigate this further.
> Best,
> Valentin
Think you for replying， I will try it.

**Comment by shangwei5** [comment]
Think you for replying， I will try it.
