### ISSUE TITLE
can you share RRDB_PSNR_x16.pth pre-trained model?

### ISSUE THREAD

**Issue by manifischer** [volflow/DeFlow#5]
Hi,
in my data the difference between LQ and HQ data is really big.
so in order that h() will not indicate from which domain (x, y) it comes from I need to do a very strong down-sampling (x8 is not enough).
you have already shared RRDB_PSNR_x8.pth and RRDB_PSNR_x4.pth pre-trained models, can you share RRDB_PSNR_x16.pth as well?
Thanks,
Mani

**Comment by volflow** [comment]
Hi Mani,

unfortunately I do not have such a model. 
However, you can simply train DeFlow without a pretrained RRDB model by setting `pretrain_model_G: ~` in the config. 
Best, 
Valentin
